version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: NotesDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: marat321
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  notespetproject:
    container_name: notespetproject
    build:
      context: .
      dockerfile: NotesPetProject/NotesPetProject/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__NotesDb: "Host=postgres;Database=NotesDb;Username=postgres;Password=marat321"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./NotesPetProject:/app
      - ~/.aspnet/https:/https:ro

volumes:
  postgres_data: