version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: NotesDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: marat321
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  notespetproject:
    container_name: notespetproject
    build:
      context: .
      dockerfile: NotesPetProject/Dockerfile  # ”казываем путь к Dockerfile
    ports:
      - "8080:8080"  # —опоставл€ем с портами из Dockerfile
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__NotesDb: "Host=postgres;Database=NotesDb;Username=postgres;Password=marat321"
    depends_on:
      - postgres
    volumes:
      - ./NotesPetProject:/app  # ƒл€ гор€чей перезагрузки в разработке
      - ~/.aspnet/https:/https:ro  # ƒл€ HTTPS в разработке

volumes:
  postgres_data: